name: Test Approval

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'     
        required: true
        default: 'dev'
      
      
      
jobs:
  Print:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ github.event.inputs.environment }}
    
  Deploy:
    runs-on: ubuntu-latest
    needs: Print
    environment: 'dev'
    steps:
    - run: echo ${{ github.event.inputs.environment }}
