name: Test Approval

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment' 
        type: choice
        required: true
        default: 'dev'
        options:
         - dev
         - qa
         - prd
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: 'variables_dev'
  
jobs:
  print:
    runs-on: ubuntu-latest
    environment: 
      name: variables_dev
    steps:
    - run: echo ${{ github.event.inputs.environment }}
    - run: echo ${{ vars.WhoAmI }}
    - run: echo ${{ vars.GOOGLE_CREDENTIALS }}
    
  deploy-dev:
    if: ${{ github.event.inputs.environment == 'dev' }} 
    runs-on: ubuntu-latest
    needs: print
    environment: 'dev'
    steps:
    - run: echo ${{ vars.WhoAmI }}
    
  deploy-qa:
    if: ${{ github.event.inputs.environment == 'qa' }} 
    runs-on: ubuntu-latest
    needs: print
    environment: 'qa'
    steps:
    - run: echo ${{ vars.WhoAmI }}
    
  deploy-prd:
    if: ${{ github.event.inputs.environment == 'prd' }}  
    runs-on: ubuntu-latest
    needs: print
    environment: 'prd'
    steps:
    - run: echo ${{ vars.WhoAmI }}
