name: Terraform

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Terraform Install Latest
      uses: hashicorp/setup-terraform@v2
      id: tfsetup
      with:
        terraform_version: latest
      
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      continue-on-error: true
      
    - name: Format Output
      run: |
        echo ${{ steps.fmt.outputs.stdout }}
        echo ${{ steps.fmt.outputs.stderr }}
        echo ${{ steps.fmt.outputs.exitcode }}
      
    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate
      
    - name: Terraform Plan
      id: plan
      run: terraform plan
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        
        
