name: Terraform

on:
  # push:
  #  branches: 
  #    - main
    
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment' 
        type: choice
        required: true
        default: 'dev'
        options:
         - dev
         - qa
         - prd
      action:
        description: 'Action' 
        type: choice
        required: true
        default: 'apply'
        options:
         - apply
         - destroy


         
jobs:
  Plan:
    runs-on: ubuntu-latest
    environment: 'variables_${{ github.event.inputs.environment }}'
    steps:
    
    # Download Last Version Repo
    - name: Checkout
      uses: actions/checkout@v3
      
    # Install Latest Version Terraform
    - name: Terraform Install Latest
      uses: hashicorp/setup-terraform@v2
      id: tfsetup
      with:
        terraform_version: latest
     
     # Terraform Initializer 
    - name: Terraform Init
      id: init
      run: terraform init
      env:
        GOOGLE_BACKEND_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      
    #  Terraform Validation
    - name: Terraform Validate
      id: validate
      run: terraform validate
    
    # Terraform Security Analysis
    - name: tfsec analyzer
      uses: aquasecurity/tfsec-action@v1.0.3
      with:
        version: latest
        additional_args: --force-all-dirs --out tfsecresult
        soft_fail: false
        github_token: ${{ secrets.GITHUB_TOKEN }}

    # Security Result Output
    - name: tfsec output 
      run: cat tfsecresult
      if: always()
      
    # Terraform Plan with credential GCP and output file tfplan
    - name: Terraform Plan - ${{ github.event.inputs.action }}
      id: plan
      run: |
      
          if [[ $TERRAFORM_TYPE -eq 'apply' ]]
          then
          
            terraform plan --out=tfplan
            
          elif [[ $TERRAFORM_TYPE -eq 'destroy' ]
          then
          
            terraform plan -destroy --out=tfplan
            
          fi
        
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        TERRAFORM_TYPE: ${{ github.event.inputs.action }}
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
       name: plan
       path: ./tfplan  

        
  Deploy:
    runs-on: ubuntu-latest
    needs: Plan 
    environment: ${{ github.event.inputs.environment }}
    steps:
    
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: plan

      # Install Latest Version Terraform
      - name: Terraform Install Latest
        uses: hashicorp/setup-terraform@v2
        id: tfsetup
        with:
          terraform_version: latest
        
      # Terraform Apply with credential GCP and output file tfplan
      - name: Terraform ${{ github.event.inputs.action }}
        id: deploy
        run: |
          
          if [[ $TERRAFORM_TYPE -eq 'apply' ]]
          then
          
            terraform apply tfplan -auto-approve
            
          elif [[ $TERRAFORM_TYPE -eq 'destroy' ]
          then
          
            terraform destroy tfplan -auto-approve
            
          fi
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          TERRAFORM_TYPE: ${{ github.event.inputs.action }}
  
        
        
