name: Terraform

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Terraform Install Latest
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: latest
        
    - name: Terraform Init
      run: terraform init
        
    - name: Terraform Plan
      run: terraform plan
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        
        
